### PR TITLE
Fix typo in contributing guide

### LINKED ISSUE #2: Remove accidental duplicate "installed" from CONTRIBUTING docs
`CONTRIBUTING.md` contains the following:

> You must have at least [Node.js](https://nodejs.org) version 4 or newer and [npm](https://npmjs.com) **installed** version 5 or newer installed.

I've highlighted in bold the word that should be removed.

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #2

### CODE REVIEW

**Review by albinekb — APPROVED** [review]

**Comment by LinusU** [comment]
ping @neocotic ☺️

**Comment by airmrcr** [comment]
Sorry, I kept meaning to reply but I'm a bit overloaded recently with work, open source projects, and personal stuff. Good catch and I think I've made the same mistake in other projects as well. I'm happy to merge this in but it needs to target the develop branch.

**Review by airmrcr — APPROVED** [review]

**Comment by airmrcr** [comment]
Merged into develop. Thanks and sorry for the delay

**Comment by LinusU** [comment]
No worries, thanks for the merge 👍

**Pull request merged**
